language: python
python:
  - "3.8"

install:
  - export RELEASE=$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/${RELEASE}/bin/linux/amd64/kubectl
  - chmod -v +x kubectl
  - sudo mv kubectl /usr/local/bin
  - mkdir ${HOME}/.kube
  - echo "$KUBE_CONFIG" | base64 --decode > ${HOME}/.kube/config

services:
  - docker

script:
  - docker build -f Dockerfile.sphinx . -t sphinx
  - docker run -v $PWD:/docs sphinx make html
  - docker build -f Dockerfile.nginx . -t splooge/docs-cstevens-io

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push splooge/docs-cstevens-io
  - sleep 5
  - /usr/local/bin/kubectl rollout restart deployment docs-cstevens-io
  - /usr/local/bin/kubectl rollout status deployment docs-cstevens-io
